"""
Django settings for Blog_App project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xw*#diin384r=-x_-aj_qwz-jx0i4eb1g7jd(y9n7_p_0gijx)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # The 'django.contrib.admin' app is added to the list of installed apps.
    # This app provides the Django administration interface, which allows you to manage your project's data.
    'django.contrib.admin',

    # The 'django.contrib.auth' app is added to the list of installed apps.
    # This app provides authentication functionality for your Django project.
    # It includes features such as user registration, login, logout, and password management.
    'django.contrib.auth',

    # The 'django.contrib.contenttypes' app is added to the list of installed apps.
    # This app provides a framework for content types, allowing you to associate models with permissions and generic relations.
    'django.contrib.contenttypes',

    # The 'django.contrib.sessions' app is added to the list of installed apps.
    # This app provides session management functionality for your Django project.
    # It allows you to store and retrieve data associated with a specific user's session.
    'django.contrib.sessions',

    # The 'django.contrib.messages' app is added to the list of installed apps.
    # This app provides a messaging framework for your Django project.
    # It allows you to store messages that can be displayed to the user on subsequent requests.
    'django.contrib.messages',

    # The 'django.contrib.staticfiles' app is added to the list of installed apps.
    # This app provides a way to manage static files (e.g., CSS, JavaScript) in your Django project.
    'django.contrib.staticfiles',

    # The 'blog.apps.BlogConfig' app is added to the list of installed apps.
    # This app is a custom app defined in the 'blog' directory of your project.
    # It contains the configuration for the 'blog' app, including its models, views, and templates.
    'blog.apps.BlogConfig',

    # The 'crispy_forms' app is added to the list of installed apps.
    # This app provides a way to easily render Django forms with Bootstrap styling.
    'crispy_forms',

    # The 'crispy_bootstrap5' app is added to the list of installed apps.
    # This app is used to enhance the form rendering in Django templates by applying Bootstrap 5 styling.
    'crispy_bootstrap5',

    # The 'django.contrib.humanize' app is added to the list of installed apps.
    # This app provides a set of template filters that can be used to format data in a human-readable way.
    # It includes filters for formatting numbers, dates, and times.
    'django.contrib.humanize',

    # The 'users.apps.UsersConfig' app is added to the list of installed apps.
    # This app is a custom app defined in the 'users' directory of your project.
    # It contains the configuration for the 'users' app, including its models, views, and templates.
    'users',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Blog_App.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Blog_App.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Authentication
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'
